# Generated by Django 3.1.2 on 2022-04-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='comorbidities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='src.comorbiditie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='src.procedure'),
        ),
    ]
