# Generated by Django 3.1.2 on 2022-04-05 22:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220403_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='in_time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 5, 22, 8, 53, 773907)),
        ),
        migrations.AddField(
            model_name='patient',
            name='seen_by_doctor',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='wait_time',
            field=models.CharField(blank=True, default='0 min', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comorbidities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.comorbiditie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_mode',
            field=models.CharField(choices=[('T', 'T'), ('FU', 'FU'), ('FOC', 'FOC')], default='Token', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.procedure'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referred_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
