# Generated by Django 3.1.2 on 2022-04-08 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20220408_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='in_time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 9, 4, 11, 29, 71412)),
        ),
    ]
